# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0906920b68148d2955782b5cc6b0b86e60b0759dc2f57a319ea4a25582a6b7d25302e3cca849d303502151ad3f9b26c3c02bffbc20c4d0e236b82990edc7c5f1

test:
  secret_key_base: 6c0f8b4620156115b6ff23723e917278c47ab9e0ab552535496e56d8b6892c17fa631698924e3ff95ffd3371d48581306d232e5a65a384969d60eaf0de4637f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
